---
title: "Predicting ICU length of stay among patients with alcohol-associated liver disease"
subtitle: "BMIN503/EPID600 Final Project"
author: "Sue Hyon Kim"
format: html
editor: visual
number-sections: true
embed-resources: true
---

------------------------------------------------------------------------

Use this template to complete your project throughout the course. Your Final Project presentation will be based on the contents of this document. Replace the title/name above and text below with your own, but keep the headers. Feel free to change the theme and other display settings, although this is not required.

## Overview {#sec-overview}

This project aims to predict the ICU length of stay for patients with alcohol-associated liver disease by applying and comparing several supervised machine learning algorithms: linear regression models, random forest, and extreme gradient boosting. This study will use the Medical Information for Intensive Care (MIMIC) -IV database. I met with Dr. Serper, who contributed domain expertise from her clinical experience as a gastroenterologist, and consulted Dr. Min regarding analytic approaches. Include a link to your final project GitHub repository.

## Introduction {#sec-introduction}

The incidence of alcohol-associated liver disease (ALD) has risen globally in recent years, especially following the intensification of psychosocial stressors during the COVID-19 pandemic. Decompensated ALD is characterized by complications, such as encephalopathy, gastrointestinal bleeding, hepatopulmonary or hepatorenal syndrome, often requiring critical care. This generates additional areas of concern, because the length of stay in the ICU is associated with healthcare expenses and resource allocation. According to a cost analysis based on ICU service costs relative to length of stay, losses are incurred in the first three days due to intensive use of diagnostic and medical resources, with profitability beginning on day four. Predicting whether a patient's ICU stay will exceed three days could help tailor care plans for patients and and optimize resource allocation, so that unnecessary interventions are reduced and resources are increased as needed based on the critical care needs of the patient.

In recognition of the importance of predicting ICU length of stay, several machine learning prediction models have been developed for this purpose. However, these previous models do not account for distinct disease traits or trajectories specific to the ALD patient population and fail to consider patient demographics, vital signs, and lab values concurrently, omiting the comprehensive range of factors that could project ICU length of stay from the outset. By integrating insights from critical care with techniques from biomedical informatics, this study aims to build machine learning models that predict ICU length of stay in relation to the three-day threshold for patients with ALD. It will utilize demographic and clinical features of the patients as predictors and evaluate the potential usefulness of the models based on their predictive accuracy.

## Methods {#sec-methods}

Describe the data used and general methodological approach used to address the problem described in the @sec-introduction. Subsequently, incorporate full R code necessary to retrieve and clean data, and perform analysis. Be sure to include a description of code so that others (including your future self) can understand what you are doing and why.

## Results {#sec-results}

Describe your results and include relevant tables, plots, and code/comments used to obtain them. You may refer to the @sec-methods as needed. End with a brief conclusion of your findings related to the question you set out to address. You can include references if you'd like, but this is not required.

## Conclusion

This the conclusion. The @sec-results can be invoked here.
